INSERT INTO documents_tag (owner_id, is_insensitive, is_inbox_tag, id, matching_algorithm, name, match, color) VALUES
    (3, true, false, 1, 4, 'Angola', '\bAngola\b', '#d41dbf'),
    (3, true, false, 2, 4, 'Bénin', '\bBénin\b|\bRépublique du Bénin\b', '#409aa7'),
    (3, true, false, 3, 4, 'Burkina Faso', '\bBurkina Faso\b', '#9d9574'),
    (3, true, false, 4, 4, 'Centrafrique', '\bCentrafrique\b|\bRépublique centrafricaine\b', '#7f9f61'),
    (3, true, false, 5, 4, 'Côte d’Ivoire', '\bCôte d''Ivoire\b|\bRépublique de Côte d''Ivoire\b', '#10a576'),
    (3, true, false, 6, 4, 'Cameroun', '\bCameroun\b|\bRepublic of Cameroon\b|\bRépublique du Cameroun\b', '#0e8606'),
    (3, true, false, 7, 4, 'RDC', '\bRDC\b|\bRépublique démocratique du Congo\b|\bDR Congo\b|\bCongo-Kinshasa\b|\bCongo-Zaire\b|\bZaire\b', '#7a9684'),
    (3, true, false, 8, 4, 'Congo', '\bCongo\b|\bRépublique du Congo\b', '#216f8f'),
    (3, true, false, 9, 4, 'Gabon', '\bGabon\b|\bRépublique Gabonaise\b', '#0dac48'),
    (3, true, false, 10, 4, 'Guinée (Conakry)', '\bGuinée\b|\bRépublique de Guinée\b|\bGuinée Conakry\b|\bConakry\b', '#352c5d'),
    (3, true, false, 11, 4, 'Ghana', '\bGhana\b|\bRepublic of Ghana\b', '#24cac2'),
    (3, true, false, 12, 4, 'Kenya', '\bKenya\b|\bRepublic of Kenya\b', '#ca2638'),
    (3, true, false, 13, 4, 'Liberia', '\bLiberia\b|\bRepublic of Liberia\b', '#d967aa'),
    (3, true, false, 14, 4, 'Madagascar', '\bMadagascar\b|\bRépublique de Madagascar\b', '#f5252d'),
    (3, true, false, 15, 4, 'Mali', '\bMali\b', '#94c67c'),
    (3, true, false, 16, 4, 'Mauritanie', '\bMauritanie\b', '#1e3676'),
    (3, true, false, 17, 4, 'Niger', '\bNiger\b|\bRépublique du Niger\b', '#8b4faf'),
    (3, true, false, 18, 4, 'Nigeria', '\bNigeria\b', '#ba24c3'),
    (3, true, false, 19, 4, 'Sénégal', '\bSénégal\b|\bRépublique du Sénégal\b', '#648209'),
    (3, true, false, 20, 4, 'Sierra Leone', '\bSierra Leone\b', '#291a53'),
    (3, true, false, 21, 4, 'Tchad', '\bTchad\b|\bChad\b', '#423334'),
    (3, true, false, 22, 4, 'Tanzanie', '\bTanzanie\b|\bUnited Republic of Tanzania\b', '#e2a8aa'),
    (3, true, false, 23, 4, 'Afrique du Sud', '\bAfrique du Sud\b|\bRepublic of South Africa\b|\bRepubliek Zuid-Afrika\b', '#182b33'),
    (3, true, false, 24, 4, 'Zimbabwe', '\bZimbabwe\b|\bRepublic of Zimbabwe\b', '#8994cc');